#include <iostream>
#include <fstream>
#include <vector>
#include <cmath>
#include <algorithm>

using namespace std;

// 1. The Math Function: Euclidean Distance
float calculateDistance(const vector<float>& vec1, const float* vec2_ptr, int dim) {
    float sum = 0.0;
    for (int i = 0; i < dim; i++) {
        float diff = vec1[i] - vec2_ptr[i];
        sum += diff * diff;
    }
    return sqrt(sum);
}

int main() {
    // MobileNetV2 outputs 1,280 dimensions
    int DIM = 1280; 

    //  Load the Single Query Vector (Generated by Streamlit when the user uploads an image)
    ifstream query_file("query.bin", ios::binary);
    if (!query_file) {
        cout << "Error: Could not load query.bin" << endl;
        return 1;
    }
    vector<float> query_vector(DIM);
    query_file.read(reinterpret_cast<char*>(query_vector.data()), DIM * sizeof(float));
    query_file.close();

    // Load the Entire Database (Generated by extract.py)
    ifstream db_file("database.bin", ios::binary | ios::ate); // Open at the end to get file size
    if (!db_file) {
        cout << "Error: Could not load database.bin" << endl;
        return 1;
    }
    streamsize size = db_file.tellg(); // Get total bytes
    db_file.seekg(0, ios::beg);        // Rewind back to the start
    
    // Calculate how many images are in the database based on the file size
    int num_images = size / (DIM * sizeof(float));
    vector<float> database(num_images * DIM);
    db_file.read(reinterpret_cast<char*>(database.data()), size);
    db_file.close();

    //  Calculate Distances
    // We store a pair: {distance, original_index_in_database}
    vector<pair<float, int>> distances;
    for (int i = 0; i < num_images; i++) {
        float dist = calculateDistance(query_vector, &database[i * DIM], DIM);
        distances.push_back({dist, i});
    }

    // Sort to find the smallest distances (most similar images)
    sort(distances.begin(), distances.end());

    //  Output the indices of the top 5 matches
    // (The Streamlit Python script will read this output)
    for (int i = 0; i < min(5, num_images); i++) {
        cout << distances[i].second << endl; 
    }

    return 0;
}